PS1="\[\033[30;1m\]\[\016\]\[\017\][\[\033[00m\]\u\[\033[34;1m\]@\[\033[00m\]\h\[\033[30;1m\]]-[\[\[\033[32;1m\]\w\[\033[30;1m\]]-[\[\033[00m\]\$(/bin/ls -Al1 | grep -v '^total' | /usr/bin/wc -l | /bin/sed 's: ::g') items, \$(/bin/ls -lah | /bin/grep -m 1 total | /bin/sed 's/total //')b\[\033[30;1m\]]\n\[\033[00m\]---\[\033[34;1m\]$ \[\033[00m\]"

alias cfv="vim ~/.vimrc"
alias cfi="vim ~/.config/i3/config"
alias cfib="vim ~/.config/i3blocks/config"
alias cfb="vim ~/.bashrc"
alias cfp="vim ~/.profile"
alias cfu="vim ~/.Xresources"
alias cft="vim ~/.tmux.conf"
alias cfx="vim ~/.xinitrc"

alias guide="vim ~/guide.txt"
alias todo="vim ~/todo.txt"
alias cfg="vim ~/Guides"
alias cfgs="vim ~/Guides/Security"
alias cfgi="vim ~/Guides/Installation"
alias cfgis="vim ~/Guides/Issues"
alias cfgc="vim ~/Guides/Configuration"

alias sci="vim ~/.scripts/i3blocks"
alias scl="vim ~/.scripts/lstatusbar"
alias sct="vim ~/.scripts/tools"

alias sob="source ~/.bashrc"
alias sop="source ~/.profile"
alias sou="xrdb -merge ~/.Xresources"

alias wifil="nmcli device wifi list"
alias wific="nmcli device wifi connect"
alias wifis="nmcli device"
alias woff="nmcli radio wifi off"
alias won="nmcli radio wifi on"

alias p="sudo pacman"
alias pup="sudo pacman -Syu"
alias pupn="sudo pacman -Syu --noconfirm"
alias pkg="sudo pacman -Qe > ~/Guides/package-list.txt"
alias pkgca="sudo pacman -Sc --noconfirm"
alias porph="sudo pacman -Rns $(sudo pacman -Qtdq)"

alias pa="sudo pakku"
alias paup="sudo pakku -Syu"
alias paupn="sudo pakku -Syu --noconfirm"
alias papkg="sudo pakku -Qe > ~/Guides/package-list.txt"
alias pakgca="sudo pakku -Sc --noconfirm"
alias parph="sudo pakku -Rns $(sudo pakku -Qtdq)"

alias netfresh="sudo systemctl restart NetworkManager"
alias susy="sudo systemctl"
alias susye="sudo systemctl enable"
alias susyd="sudo systemctl disable"
alias susysa="sudo systemctl start"
alias susyso="sudo systemctl stop"
alias susyr="sudo systemctl restart"
alias susyre="sudo systemctl reset-failed"
alias systat="systemctl status"
alias syslst="systemctl list-unit-files"
alias sysfai="systemctl --failed --all"
alias sysser="systemctl --type=service"

alias symbrk="find / -xtype l -print"
alias diskur="ncdu /"

alias vlab="ssh z5197058@login.cse.unsw.edu.au"
alias vlabf="sftp z5197058@login.cse.unsw.edu.au"

alias vlcn"=vlc -I ncurses"
alias reddit="rtv --no-flash"

alias s="sudo"
alias v="vim"
alias sv="sudo vim"
alias r="ranger"
alias sr="sudo ranger"

alias lsa="ls -Al --color=auto" 
alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
