#!/bin/bash

#case $BLOCK_BUTTON in
#	1) $TERMINAL -hold -e bash -c "htop && bash";;
#	3) pgrep -x dunst >/dev/null && notify-send -u low "<b>CPU Temperature Module</b>" "Left click - htop
#Right click - show usage message
#";;
#esac

temp=$(sensors | awk '/Core 0/ {print $3}' | cut -d'+' -f2 | sed 's/\..*//') 

if [ "$temp" -ge 105 ]; then
	color="#FF0025" # red
elif [ "$temp" -ge 90 ]; then
	color="#A43261" #color1
elif [ "$temp" -ge 70 ]; then
	color="#FFA7F6" #color13
elif [ "$temp" -ge 50 ]; then
	color="#3BD6FF" #color10
else 
	color="#006CA5" #color2
fi

tstr=$(sensors | awk '/Core 0/ {print $3}' | cut -d'+' -f2)

printf "<span foreground='%s'>%s</span>" "$color" "$tstr"
