#!/bin/bash

case $BLOCK_BUTTON in
	1) $TERMINAL -hold -e bash -c "sudo pakku -Syu --noconfirm && bash";;
	2) $TERMINAL -hold -e bash -c "sudo pakku -Qu | less && bash";;
	3) pgrep -x dunst >/dev/null && notify-send -u low "<b>System Update Module</b>" "Left click - update system
Middle click - show packages that have updates
Right click - show usage message
";;
esac

sudo pakku -Syw > /dev/null
count=$(sudo pakku -Qu | wc -l)

if [ "$count" = "0" ]; then
	message="Updated"
	color="#3BD6FF" #color10
	printf "<span foreground='%s'>%s</span>" "$color" "$message"

elif [ "$count" = "1" ]; then
	message="update"
	color="#A43261" #color1
	printf "<span foreground='%s'>%s %s</span>" "$color" "$count" "$message"

else
	message="updates"
	color="#A43261" #color1
	printf "<span foreground='%s'>%s %s</span>" "$color" "$count" "$message"
fi
