#!/bin/bash

case $BLOCK_BUTTON in
	1) $TERMINAL -hold -e bash -c "nmtui && bash";;
	3) pgrep -x dunst >/dev/null && notify-send -u low "<b>Wifi Module</b>" "Left click - open nmtui
Right click - show usage message
";;
esac

device=$(nmcli device | grep -o '^wlp4s0.*' | awk '{print $1}')
type=$(nmcli device | grep -o '^wlp4s0.*' | awk '/wlp4s0/ {print $2}')
state=$(nmcli device | grep -o '^wlp4s0.*' | awk '/wlp4s0/ {print $3}')
conn=$(nmcli device | grep -o '^wlp4s0.*' | awk '/wlp4s0/' | awk '{for(i=4;i<NF;++i)printf "%s ", $i} {printf "%s", $NF}')

if [ "$state" = "connected" ]; then
	color="#3BD6FF" #color10
elif [ "$state" = "connecting" ]; then
	color="#D5B8FF" #color12
elif [ "$state" = "disconnected" ]; then
	color="#6751A6" #color4"
else
	color="#FF0025" #red
fi

printf "<span foreground='%s'>W: %s</span>" "$color" "$conn"
